### ISSUE TITLE
Metallurgy/Thermal Expansion tools  conflict

### ISSUE THREAD

**Issue by chibiushi** [MC-Soupcup/MadCast-Mimic#4]
I cannot make the TE stuff because it share's recipes

**Comment by MC-Soupcup** [comment]
Sorry for not getting back sooner, but to be honest, I don't see this as much of an issue since they share pretty much the same stats. For instance, copper swords from Metallurgy have +5 damage, TE's are +4.5, similar durability. Silver and Electrum are the same, even the armor sets give the same protection, for the most part. This is just a result of having both of these mods adding tools of the same metal type. 

Now I suppose I could make a separate recipe for each type of sword or whatever, or even just disable the recipe for one type of sword/etc., but that just seems unnecessary, unless there's specific recipes that use say, a TE specific item (like how Invar ones can be used in some recipes, but these aren't overwritten). If that's the case, which I can't find as of yet, I'll likely leave it as-is.

Or is there some specific functionality that some tools do that I don't know about that you can't use because of this?

**Comment by chibiushi** [comment]
Nope, just grabbing a shovel cause I needed a shovel and I grabbed a random ingot. The crafting grid showed it crafting te shovel and I got metallurgy so I added the bug.

**Comment by MC-Soupcup** [comment]
Alright then, good to know though.
